-- Lista de cidades do interior de São Paulo
-- Execute este SQL no seu banco de dados

INSERT INTO cidades (nome, uf, slug, ativo) VALUES
('Ribeirão Preto', 'SP', 'ribeirao-preto-sp', 1),
('Sertãozinho', 'SP', 'sertaozinho-sp', 1),
('Franca', 'SP', 'franca-sp', 1),
('Araraquara', 'SP', 'araraquara-sp', 1),
('Bauru', 'SP', 'bauru-sp', 1),
('Piracicaba', 'SP', 'piracicaba-sp', 1),
('Campinas', 'SP', 'campinas-sp', 1),
('Sorocaba', 'SP', 'sorocaba-sp', 1),
('Jundiaí', 'SP', 'jundiai-sp', 1),
('Americana', 'SP', 'americana-sp', 1),
('Limeira', 'SP', 'limeira-sp', 1),
('São Carlos', 'SP', 'sao-carlos-sp', 1),
('Taubaté', 'SP', 'taubate-sp', 1),
('São José dos Campos', 'SP', 'sao-jose-dos-campos-sp', 1),
('Mogi das Cruzes', 'SP', 'mogi-das-cruzes-sp', 1),
('Santos', 'SP', 'santos-sp', 1),
('Guarulhos', 'SP', 'guarulhos-sp', 1),
('São Bernardo do Campo', 'SP', 'sao-bernardo-do-campo-sp', 1),
('Barueri', 'SP', 'barueri-sp', 1),
('Osasco', 'SP', 'osasco-sp', 1),
('Itu', 'SP', 'itu-sp', 1),
('Indaiatuba', 'SP', 'indaiatuba-sp', 1),
('Hortolândia', 'SP', 'hortolandia-sp', 1),
('Sumaré', 'SP', 'sumare-sp', 1),
('Rio Claro', 'SP', 'rio-claro-sp', 1),
('Araras', 'SP', 'araras-sp', 1),
('Mogi Guaçu', 'SP', 'mogi-guacu-sp', 1),
('Mogi Mirim', 'SP', 'mogi-mirim-sp', 1),
('Pirassununga', 'SP', 'pirassununga-sp', 1),
('São João da Boa Vista', 'SP', 'sao-joao-da-boa-vista-sp', 1),
('Votuporanga', 'SP', 'votuporanga-sp', 1),
('Catanduva', 'SP', 'catanduva-sp', 1),
('Barretos', 'SP', 'barretos-sp', 1),
('Jaboticabal', 'SP', 'jaboticabal-sp', 1),
('Batatais', 'SP', 'batatais-sp', 1),
('Ituverava', 'SP', 'ituverava-sp', 1),
('Orlândia', 'SP', 'orlandia-sp', 1),
('Guariba', 'SP', 'guariba-sp', 1),
('Pitangueiras', 'SP', 'pitangueiras-sp', 1),
('Bebedouro', 'SP', 'bebedouro-sp', 1),
('Monte Alto', 'SP', 'monte-alto-sp', 1),
('Taquaritinga', 'SP', 'taquaritinga-sp', 1),
('Matão', 'SP', 'matao-sp', 1),
('Ibitinga', 'SP', 'ibitinga-sp', 1),
('Itápolis', 'SP', 'itapolis-sp', 1),
('Boa Esperança do Sul', 'SP', 'boa-esperanca-do-sul-sp', 1),
('Dobrada', 'SP', 'dobrada-sp', 1),
('Tabatinga', 'SP', 'tabatinga-sp', 1),
('Nova Europa', 'SP', 'nova-europa-sp', 1),
('Gavião Peixoto', 'SP', 'gaviao-peixoto-sp', 1),
('Motuca', 'SP', 'motuca-sp', 1),
('Rincão', 'SP', 'rincao-sp', 1),
('Guarantã', 'SP', 'guaranta-sp', 1),
('Borborema', 'SP', 'borborema-sp', 1),
('Trabiju', 'SP', 'trabiju-sp', 1),
('Américo Brasiliense', 'SP', 'americo-brasiliense-sp', 1),
('Santa Lúcia', 'SP', 'santa-lucia-sp', 1),
('Ribeirão Bonito', 'SP', 'ribeirao-bonito-sp', 1),
('Boa Vista da Aparecida', 'SP', 'boa-vista-da-aparecida-sp', 1)
ON DUPLICATE KEY UPDATE nome=nome;

